from .crear_conexion import abrir_conexion
from .gestion_peliculas import obtener_peliculas_bd,agregar_pelicula_bd,editar_pelicula_bd,eliminar_pelicula_bd
from .gestion_salas import obtener_salas_bd,agregar_sala_bd,editar_sala_bd,eliminar_sala_bd
from .gestion_funciones import obtener_funciones_bd